### ISSUE TITLE
Text Wrapping for the Key Summary is broken

### ISSUE THREAD

**Issue by ramsowo** [hurtonypeter/altmanager2#3]
I believe old version of this addon had text wrapping for the "highest M+ section" and it is no longer working. 
![image](https://user-images.githubusercontent.com/103061771/162636924-621c6de3-60e8-406a-9c69-8d16b506148a.png)

**Comment by hurtonypeter** [comment]
I'm not sure, ever since I'm using it (shadowlands 9.0.2), it was always like this. I also didn't change any of this code, but I agree the current display is pretty bad, cuz u can't tell
- how many you need for the 3rd vault slot
- how high will be the 3rd vault slot

Maybe you can send a pr?

**Comment by hurtonypeter** [comment]
I'm not really sure why this isn't working, it turns out you were right, there was a line break here. It is not working since shadowlands, but I found the line break char in the code. The problem isn't that it doesn't break the lines, but the UI trimmes the whole table if the data is more than one line, so that's why the "...". This code is pretty messy, so right now I created a hotfix to not break the line + have 20 more pixels to the width, so they don't bump into each other.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/4543944/163077618-3229a49b-3be5-463e-ad87-b0c5ee664ceb.png">
